image: ubuntu
stack: python 3.6

version: 1.0.0.{build}

environment:
  AWS_ACCESS_KEY_ID:
    secure: s4eDNMGAAUTE4383LMG6Hy7yRNtDlIEEYtxy7XsiGb4=
  AWS_SECRET_ACCESS_KEY:
    secure: bx7w89m6gjfpGpQhhD43bhRNq2pJIZG18jx8mc4LWLPDgG5Hqq3tvMq/x9dwQ6Ax

install:
  - sh: pip install -r requirements.txt -q
  - sh: sudo chmod -x ./build.sh
  - sh: bash ./build.sh

for:
-
  branches:
    only:
      - master
