image: ubuntu

version: 1.0.0.{build}

environment:
  AWS_ACCESS_KEY_ID:
    secure: s4eDNMGAAUTE4383LMG6Hy7yRNtDlIEEYtxy7XsiGb4=
  AWS_SECRET_ACCESS_KEY:
    secure: bx7w89m6gjfpGpQhhD43bhRNq2pJIZG18jx8mc4LWLPDgG5Hqq3tvMq/x9dwQ6Ax

install:
  - sh: alias python=python3
  - sh: pip install -r requirements.txt
  - sh: pip install awscli
  - sh: pip freeze
  - sh: awscli configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - sh: awscli configure set secret_access_key $AWS_SECRET_ACCESS_KEY
  - sh: awscli configure set default.region eu-west-1
  - sh: aws s3 cp --recursive ./ s3://crypto-deployment-code/{APPVEYOR_REPO_BRANCH}


for:
-
  branches:
    only:
      - master

  artifacts:
    path: pipeline/*.py, pipeline/*/*.py
    name: pipeline

  deploy:
    provider: S3
    access_key_id:
      secure: s4eDNMGAAUTE4383LMG6Hy7yRNtDlIEEYtxy7XsiGb4=
    secret_access_key:
      secure: bx7w89m6gjfpGpQhhD43bhRNq2pJIZG18jx8mc4LWLPDgG5Hqq3tvMq/x9dwQ6Ax
    bucket: s3-crypto-deployment-code
    region: eu-west-1
    unzip: false
    set_public: false
    folder: pipeline/current
    artifact: pipeline